/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author James
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        seticon();
        show_user();
    }
   
   public ArrayList<Sets> userList(){
        ArrayList<Sets> userList = new ArrayList<>();
        try{
        Database db = new Database();
        String query="select * from Medicine";
        Statement st =db.conn.createStatement();
        ResultSet rs = st.executeQuery(query);
        Sets user;
        while(rs.next()){
            user=new Sets(rs.getInt("medicine_id"),
                    rs.getString("medicine_name"),
                    rs.getString("company_name"),
                    rs.getString("pack_size"),
                    rs.getDouble("quantity"),
                    rs.getDouble("unit_price"),
                    rs.getDouble("total_amount"),
                    rs.getString("expiry_date")
            );
            userList.add(user);
        }
        }
        catch(Exception ex){
        }
        return userList;
    }
    
    public void show_user(){
        ArrayList<Sets> list = userList();
        DefaultTableModel model =(DefaultTableModel)jtable.getModel();
        Object[] row = new Object[8];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getmedicine_name();
            row[2]=list.get(i).getcompany_name();
            row[3]=list.get(i).getpack_size();
            row[4]=list.get(i).getquantity();
            row[5]=list.get(i).getunnit_price();
            row[6]=list.get(i).gettotal_amount();
            row[7]=list.get(i).getexpiry_date();
            
            model.addRow(row);
        }
    }
      
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quantityTxt1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        companyTxt = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        medicineTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        expTxt = new javax.swing.JTextField();
        unitTxt = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        quantityTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        packTxt = new javax.swing.JTextField();
        searchTxt = new javax.swing.JTextField();

        quantityTxt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        quantityTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTxt1KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G&K Pharmacy");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(63, 73, 195));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("G&K Pharmacy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Medicine Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Company");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Unit Price");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Expiry Date");

        companyTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn.setBackground(new java.awt.Color(63, 73, 195));
        btn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setLabel("Add");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        medicineTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medicineTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                medicineTxtFocusLost(evt);
            }
        });
        medicineTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medicineTxtKeyReleased(evt);
            }
        });

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N", "Medicine Name", "Company", "Pack Size", "Quantity", "Unit Price", "Amount", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable.setRowHeight(jtable.getRowHeight() + 20);
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);
        if (jtable.getColumnModel().getColumnCount() > 0) {
            jtable.getColumnModel().getColumn(0).setMaxWidth(30);
            jtable.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        btn1.setBackground(new java.awt.Color(204, 0, 255));
        btn1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Export to CSV");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 204, 51));
        btn2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("Update");
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        expTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        unitTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        unitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitTxtActionPerformed(evt);
            }
        });
        unitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitTxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unitTxtKeyTyped(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 51, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Delete");
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(153, 153, 153));
        btn4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("Clear All");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        quantityTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });
        quantityTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityTxtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Pack Size");

        packTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        packTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                packTxtKeyTyped(evt);
            }
        });

        searchTxt.setForeground(new java.awt.Color(153, 153, 153));
        searchTxt.setText("Search..");
        searchTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTxtFocusLost(evt);
            }
        });
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(medicineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(companyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(packTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(unitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(medicineTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(companyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(packTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(unitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
       if (medicineTxt.getText().equals("") || companyTxt.getText().equals("") || packTxt.getText().equals("") || quantityTxt.getText().equals("") || unitTxt.getText().equals("") || expTxt.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Please enter all data!");
       }
       else{
           try {
                Database db=new Database();
                double total_amount;
                total_amount =  Double.parseDouble(quantityTxt.getText()) *  Double.parseDouble(unitTxt.getText());
                int result = db.save(medicineTxt.getText(), companyTxt.getText(),packTxt.getText(),Double.parseDouble(quantityTxt.getText()),Double.parseDouble(unitTxt.getText()),total_amount,expTxt.getText());
                if(result>0)
                {
                    
                    DefaultTableModel model = (DefaultTableModel)jtable.getModel();
                    model.setRowCount(0);
                    show_user();
                    
                     JOptionPane.showMessageDialog(null,"Added");
                     
                     medicineTxt.setText("");
                     companyTxt.setText("");
                     packTxt.setText("");
                     quantityTxt.setText("");
                     unitTxt.setText("");
                     expTxt.setText("");
                      
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Unable to save");
                }
            } catch (Exception e) {
            }
           
       }
      
    }//GEN-LAST:event_btnActionPerformed

    private void quantityTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTxtKeyTyped
       char c = evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_PERIOD)){
           evt.consume();
       }
    }//GEN-LAST:event_quantityTxtKeyTyped

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "csv","gif");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Specify a file save");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            //lets write to file
         
            try {
                  FileWriter fw = new FileWriter(fileToSave);
                  
                  for (int i = 0; i < jtable.getColumnCount(); i++) {
            fw.write(jtable.getColumnName(i) + ",");
        }
                   fw.write("\n");
                BufferedWriter bw = new BufferedWriter(fw);
                for(int i = 0; i < jtable.getRowCount();i++) {
                    for(int j = 0; j < jtable.getColumnCount(); j++) {
                        //write
                        bw.write(jtable.getValueAt(i, j).toString()+",");
                    }
                    bw.newLine();//record per line 
                }
                JOptionPane.showMessageDialog(this, "Successfully exported!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                bw.close();
                fw.close();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(this, "ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        
        
      if (medicineTxt.getText().equals("") || companyTxt.getText().equals("") || packTxt.getText().equals("") || quantityTxt.getText().equals("") || unitTxt.getText().equals("") || expTxt.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Please enter all data!");
       }
       else{
           try {
                int row = jtable.getSelectedRow();
                String value = (jtable.getModel().getValueAt(row, 0).toString()); 
                Database db = new Database();
                double total_amount =  Double.parseDouble(quantityTxt.getText()) *  Double.parseDouble(unitTxt.getText());
                int result = db.update_medicine(medicineTxt.getText(), companyTxt.getText(),packTxt.getText(),Double.parseDouble(quantityTxt.getText()),Double.parseDouble(unitTxt.getText()),total_amount,expTxt.getText(),value);
                if(result>0)
                {
                    DefaultTableModel model = (DefaultTableModel)jtable.getModel();
                    model.setRowCount(0);
                    show_user();
                    JOptionPane.showMessageDialog(null,"Updated");
                     
                     medicineTxt.setText("");
                     companyTxt.setText("");
                     packTxt.setText("");
                     quantityTxt.setText("");
                     unitTxt.setText("");
                     expTxt.setText("");
                 }
                else
                {
                    JOptionPane.showMessageDialog(null,"Unable to save");
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
           
       }
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        int i = jtable.getSelectedRow();
        TableModel model = jtable.getModel();
        medicineTxt.setText(model.getValueAt(i, 1).toString());
         companyTxt.setText(model.getValueAt(i, 2).toString());
          packTxt.setText(model.getValueAt(i, 3).toString());
          quantityTxt.setText(model.getValueAt(i, 4).toString());
          unitTxt.setText(model.getValueAt(i, 5).toString());
         expTxt.setText(model.getValueAt(i, 7).toString());
  
    }//GEN-LAST:event_jtableMouseClicked

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
//          if (medicineTxt.getText().equals("") && companyTxt.getText().equals("") && packTxt.getText().equals("") && quantityTxt.getText().equals("") && unitTxt.getText().equals("") && expTxt.getText().equals("")){
//           JOptionPane.showMessageDialog(this, "Please select data to delete!");
//            }
//        else{
//        int a = JOptionPane.showConfirmDialog(null,"Do you sure want to delete this ?","Delete",JOptionPane.YES_NO_OPTION);
//        if(a==0){ 
//              Database db = new Database();
//              int row = jtable.getSelectedRow();
//              String value = (jtable.getModel().getValueAt(row, 0).toString());
//              int result = db.delete(value);
//              if(result>0)
//                  {
//                      DefaultTableModel model = (DefaultTableModel)jtable.getModel();
//                      model.setRowCount(0);
//                      show_user();
//                      JOptionPane.showMessageDialog(null,"Deleted");
//
//                       medicineTxt.setText("");
//                       companyTxt.setText("");
//                       packTxt.setText("");
//                       quantityTxt.setText("");
//                       unitTxt.setText("");
//                       expTxt.setText("");
//                   }
//                  else
//                  {
//                      JOptionPane.showMessageDialog(null,"Unable to delete");
//                  }
//            }
//         }
        
                  if (medicineTxt.getText().equals("") && companyTxt.getText().equals("") && packTxt.getText().equals("") && quantityTxt.getText().equals("") && unitTxt.getText().equals("") && expTxt.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Please select data to delete!");
            }
                  
        else{
          int a = JOptionPane.showConfirmDialog(null,"Do you sure want to delete this ?","Delete",JOptionPane.YES_NO_OPTION);
        if(a==0){ 
        int row = jtable.getSelectedRow();
       if(row!=-1)
       {
           String NOMER = jtable.getValueAt(row, 0).toString();
           System.out.println(NOMER);
           String sql = "DELETE FROM Medicine WHERE medicine_id='"+NOMER+"'";
           
           String resetno = "ALTER TABLE Medicine DROP medicine_id";
           String consecutivenumbers="ALTER TABLE Medicine ADD medicine_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST";
           
           try {
               Database.koneksiDb().createStatement().execute(sql);
               Database.koneksiDb().createStatement().execute(resetno);
               Database.koneksiDb().createStatement().execute(consecutivenumbers);
               
    
                DefaultTableModel model = (DefaultTableModel)jtable.getModel();
                      model.setRowCount(0);
                      show_user();
                      JOptionPane.showMessageDialog(null,"Deleted");

                       medicineTxt.setText("");
                       companyTxt.setText("");
                       packTxt.setText("");
                       quantityTxt.setText("");
                       unitTxt.setText("");
                       expTxt.setText("");
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Unable to delete");
           }
           
       }
        }
    }
        
        
        
        
        
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        medicineTxt.setText("");
        companyTxt.setText("");
          packTxt.setText("");
        quantityTxt.setText("");
        unitTxt.setText("");
        expTxt.setText("");
    }//GEN-LAST:event_btn4ActionPerformed

    private void unitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTxtActionPerformed

    private void quantityTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTxt1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxt1KeyTyped

    private void packTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_packTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_packTxtKeyTyped

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void unitTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitTxtKeyTyped
      char c = evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_PERIOD)){
           evt.consume();
       }
    }//GEN-LAST:event_unitTxtKeyTyped

    private void unitTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitTxtKeyPressed

    private void medicineTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medicineTxtKeyReleased
      
    }//GEN-LAST:event_medicineTxtKeyReleased

    private void medicineTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicineTxtFocusGained
       
    }//GEN-LAST:event_medicineTxtFocusGained

    private void medicineTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicineTxtFocusLost
       
    }//GEN-LAST:event_medicineTxtFocusLost

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        DefaultTableModel table = (DefaultTableModel)jtable.getModel();
       String search = searchTxt.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jtable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" +search));
    }//GEN-LAST:event_searchTxtKeyReleased

    private void searchTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusGained
        if (searchTxt.getText().equals("Search..")){
            searchTxt.setText("");
            searchTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchTxtFocusGained

    private void searchTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTxtFocusLost
        if (searchTxt.getText().equals("")){
            searchTxt.setText("Search..");
            searchTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchTxtFocusLost

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void searchTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyTyped
       searchTxt.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_searchTxtKeyTyped

    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
        
    }
    
    private void seticon(){
       Image icon = Toolkit.getDefaultToolkit().getImage("img/gnk.png");  
        setIconImage(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JTextField companyTxt;
    private javax.swing.JTextField expTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable;
    private javax.swing.JTextField medicineTxt;
    private javax.swing.JTextField packTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JTextField quantityTxt1;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField unitTxt;
    // End of variables declaration//GEN-END:variables

    


}
